### ISSUE TITLE
Cant login

### ISSUE THREAD

**Issue by evilcommand** [LoriqueNET/KillFeed#15]
After i enterd my lingin it says please wait
I laft it for 2 hour and still please wait 
Any ideas how to fix it ?

**Comment by lorique** [comment]
Hey Evilcommand. 

I sure can. if you can send me the email you used to sign up with, i will assign you a new password. The password reset button has yet to be implemented due to gross neglect on my part, so I have to do it manually. If you send your email to the killfeed-at-lorique-dot-net mail in the app, and in the mass email i send out, i will respond with your new password.

-- KillFeed

**Comment by lorique** [comment]
Oh... sorry. Misread.. yeah if you close the app completely, and open it again, the thing resets. And you can try logging in again.

**Comment by evilcommand** [comment]
hey tnx for reply so fast
i closed it and retyed notting i even restarted my phone couple times still notting
i included my printscrn it keeps loading for ever
my login email: wesleygamer15@live.nl
any ideas ? it worked fine before and i really love the app



Wesley  a: Asmusstraat 33 Hellevoetsluis        w: https://evilcommand.jimdo.com/
Gamer   p: 0628393039   e: wesleygamer15@live.nl
.       [X] <http://.>


Op 8-3-2017 09:31:33, Martin Ricken <notifications@github.com> schreef:

Oh... sorry. Misread.. yeah if you close the app completely, and open it again, the thing resets. And you can try logging in again.

**Comment by lorique** [comment]
Closing issue, since its resolved.
